import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppBar from "@/app/components/AppBar";
import AppFooter from "@/app/components/AppFooter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased max-h-screen overflow-auto bg-[image:var(--gradient-main)] bg-no-repeat text-cyan-400`}
      >
        <div className="h-screen flex flex-col gap-4 overflow-auto">
          <AppBar/>
          <main className="container px-4 md:px-8 lg:px-0 mx-auto flex-grow">
            {children}
          </main>
          <AppFooter/>
        </div>
      </body>
    </html>
  );
}
